# Generated by Django 4.2.7 on 2024-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_review_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('board', models.CharField(max_length=300)),
                ('std', models.CharField(max_length=300)),
                ('sclname', models.CharField(max_length=300)),
                ('scltime', models.CharField(max_length=300)),
                ('marks', models.CharField(max_length=300)),
            ],
        ),
    ]
