# Generated by Django 4.2.7 on 2024-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_enquiry_board_alter_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1, null=True),
        ),
    ]
