# Generated by Django 4.2.7 on 2024-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_enquiry_board_alter_enquiry_scltime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='board',
            field=models.CharField(choices=[('CBSC', 'CBSC'), ('ISCE', 'ISCE'), ('SSC', 'SSC'), ('SEMI', 'SEMI'), ('COLLEGE', 'COLLEGE')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='scltime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='std',
            field=models.CharField(choices=[('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=6, null=True),
        ),
    ]
